pipeline {
    agent any
	tools{
		maven "maven_3_5_0"
	}
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Puedes agregar aquí comandos específicos para construir tu aplicación
                    // Por ejemplo: ./gradlew build o mvn clean install
                    bat 'mvn clean install'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Detener y eliminar el contenedor existente (si existe)
                    bat 'docker stop springbootmysqlproject || exit 0'
                    bat 'docker rm springbootmysqlproject || exit 0'

                    // Iniciar el contenedor con la nueva imagen desde DockerHub
                    bat 'docker run -d --name springbootmysqlproject -p 8080:8080 maxicrah/springbootmysql:latest'
                }
            }
        }
    }
}
